schema:
  - https://docs.github.com/public/fpt/schema.docs.graphql:
      headers:
        Authorization: Bearer ${GITHUB_TOKEN}
        User-Agent: github-viewer

documents:
  - "src/**/*.{ts,tsx}"
  - "!src/**/*.d.ts"

extensions:
  languageService:
    cacheSchemaFileForLookup: true
