/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerRepoRouteRouteImport } from './routes/$owner.$repo/route'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner.$repo/index'
import { Route as OwnerRepoPullsRouteImport } from './routes/$owner.$repo/pulls'
import { Route as OwnerRepoIssuesRouteImport } from './routes/$owner.$repo/issues'
import { Route as OwnerRepoPullNumberRouteRouteImport } from './routes/$owner.$repo/pull/$number/route'
import { Route as OwnerRepoPullNumberIndexRouteImport } from './routes/$owner.$repo/pull/$number/index'
import { Route as OwnerRepoPullNumberFilesRouteImport } from './routes/$owner.$repo/pull/$number/files'
import { Route as OwnerRepoPullNumberCommitsRouteImport } from './routes/$owner.$repo/pull/$number/commits'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoRouteRoute = OwnerRepoRouteRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoRouteRoute,
} as any)
const OwnerRepoPullsRoute = OwnerRepoPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => OwnerRepoRouteRoute,
} as any)
const OwnerRepoIssuesRoute = OwnerRepoIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => OwnerRepoRouteRoute,
} as any)
const OwnerRepoPullNumberRouteRoute =
  OwnerRepoPullNumberRouteRouteImport.update({
    id: '/pull/$number',
    path: '/pull/$number',
    getParentRoute: () => OwnerRepoRouteRoute,
  } as any)
const OwnerRepoPullNumberIndexRoute =
  OwnerRepoPullNumberIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OwnerRepoPullNumberRouteRoute,
  } as any)
const OwnerRepoPullNumberFilesRoute =
  OwnerRepoPullNumberFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => OwnerRepoPullNumberRouteRoute,
  } as any)
const OwnerRepoPullNumberCommitsRoute =
  OwnerRepoPullNumberCommitsRouteImport.update({
    id: '/commits',
    path: '/commits',
    getParentRoute: () => OwnerRepoPullNumberRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/$owner/$repo': typeof OwnerRepoRouteRouteWithChildren
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRouteRouteWithChildren
  '/$owner/$repo/pull/$number/commits': typeof OwnerRepoPullNumberCommitsRoute
  '/$owner/$repo/pull/$number/files': typeof OwnerRepoPullNumberFilesRoute
  '/$owner/$repo/pull/$number/': typeof OwnerRepoPullNumberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/pull/$number/commits': typeof OwnerRepoPullNumberCommitsRoute
  '/$owner/$repo/pull/$number/files': typeof OwnerRepoPullNumberFilesRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/$owner/$repo': typeof OwnerRepoRouteRouteWithChildren
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/pull/$number': typeof OwnerRepoPullNumberRouteRouteWithChildren
  '/$owner/$repo/pull/$number/commits': typeof OwnerRepoPullNumberCommitsRoute
  '/$owner/$repo/pull/$number/files': typeof OwnerRepoPullNumberFilesRoute
  '/$owner/$repo/pull/$number/': typeof OwnerRepoPullNumberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/$owner/$repo'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/'
    | '/$owner/$repo/pull/$number'
    | '/$owner/$repo/pull/$number/commits'
    | '/$owner/$repo/pull/$number/files'
    | '/$owner/$repo/pull/$number/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo'
    | '/$owner/$repo/pull/$number/commits'
    | '/$owner/$repo/pull/$number/files'
    | '/$owner/$repo/pull/$number'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/$owner/$repo'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/'
    | '/$owner/$repo/pull/$number'
    | '/$owner/$repo/pull/$number/commits'
    | '/$owner/$repo/pull/$number/files'
    | '/$owner/$repo/pull/$number/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  OwnerRepoRouteRoute: typeof OwnerRepoRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo': {
      id: '/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof OwnerRepoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof OwnerRepoRouteRoute
    }
    '/$owner/$repo/pulls': {
      id: '/$owner/$repo/pulls'
      path: '/pulls'
      fullPath: '/$owner/$repo/pulls'
      preLoaderRoute: typeof OwnerRepoPullsRouteImport
      parentRoute: typeof OwnerRepoRouteRoute
    }
    '/$owner/$repo/issues': {
      id: '/$owner/$repo/issues'
      path: '/issues'
      fullPath: '/$owner/$repo/issues'
      preLoaderRoute: typeof OwnerRepoIssuesRouteImport
      parentRoute: typeof OwnerRepoRouteRoute
    }
    '/$owner/$repo/pull/$number': {
      id: '/$owner/$repo/pull/$number'
      path: '/pull/$number'
      fullPath: '/$owner/$repo/pull/$number'
      preLoaderRoute: typeof OwnerRepoPullNumberRouteRouteImport
      parentRoute: typeof OwnerRepoRouteRoute
    }
    '/$owner/$repo/pull/$number/': {
      id: '/$owner/$repo/pull/$number/'
      path: '/'
      fullPath: '/$owner/$repo/pull/$number/'
      preLoaderRoute: typeof OwnerRepoPullNumberIndexRouteImport
      parentRoute: typeof OwnerRepoPullNumberRouteRoute
    }
    '/$owner/$repo/pull/$number/files': {
      id: '/$owner/$repo/pull/$number/files'
      path: '/files'
      fullPath: '/$owner/$repo/pull/$number/files'
      preLoaderRoute: typeof OwnerRepoPullNumberFilesRouteImport
      parentRoute: typeof OwnerRepoPullNumberRouteRoute
    }
    '/$owner/$repo/pull/$number/commits': {
      id: '/$owner/$repo/pull/$number/commits'
      path: '/commits'
      fullPath: '/$owner/$repo/pull/$number/commits'
      preLoaderRoute: typeof OwnerRepoPullNumberCommitsRouteImport
      parentRoute: typeof OwnerRepoPullNumberRouteRoute
    }
  }
}

interface OwnerRepoPullNumberRouteRouteChildren {
  OwnerRepoPullNumberCommitsRoute: typeof OwnerRepoPullNumberCommitsRoute
  OwnerRepoPullNumberFilesRoute: typeof OwnerRepoPullNumberFilesRoute
  OwnerRepoPullNumberIndexRoute: typeof OwnerRepoPullNumberIndexRoute
}

const OwnerRepoPullNumberRouteRouteChildren: OwnerRepoPullNumberRouteRouteChildren =
  {
    OwnerRepoPullNumberCommitsRoute: OwnerRepoPullNumberCommitsRoute,
    OwnerRepoPullNumberFilesRoute: OwnerRepoPullNumberFilesRoute,
    OwnerRepoPullNumberIndexRoute: OwnerRepoPullNumberIndexRoute,
  }

const OwnerRepoPullNumberRouteRouteWithChildren =
  OwnerRepoPullNumberRouteRoute._addFileChildren(
    OwnerRepoPullNumberRouteRouteChildren,
  )

interface OwnerRepoRouteRouteChildren {
  OwnerRepoIssuesRoute: typeof OwnerRepoIssuesRoute
  OwnerRepoPullsRoute: typeof OwnerRepoPullsRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
  OwnerRepoPullNumberRouteRoute: typeof OwnerRepoPullNumberRouteRouteWithChildren
}

const OwnerRepoRouteRouteChildren: OwnerRepoRouteRouteChildren = {
  OwnerRepoIssuesRoute: OwnerRepoIssuesRoute,
  OwnerRepoPullsRoute: OwnerRepoPullsRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
  OwnerRepoPullNumberRouteRoute: OwnerRepoPullNumberRouteRouteWithChildren,
}

const OwnerRepoRouteRouteWithChildren = OwnerRepoRouteRoute._addFileChildren(
  OwnerRepoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  OwnerRepoRouteRoute: OwnerRepoRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
