/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerRepoNumberRouteImport } from './routes/$owner.$repo.$number'
import { Route as OwnerRepoNumberIndexRouteImport } from './routes/$owner.$repo.$number.index'
import { Route as OwnerRepoNumberFilesRouteImport } from './routes/$owner.$repo.$number.files'
import { Route as OwnerRepoNumberCommitsRouteImport } from './routes/$owner.$repo.$number.commits'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoNumberRoute = OwnerRepoNumberRouteImport.update({
  id: '/$owner/$repo/$number',
  path: '/$owner/$repo/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoNumberIndexRoute = OwnerRepoNumberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoNumberRoute,
} as any)
const OwnerRepoNumberFilesRoute = OwnerRepoNumberFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => OwnerRepoNumberRoute,
} as any)
const OwnerRepoNumberCommitsRoute = OwnerRepoNumberCommitsRouteImport.update({
  id: '/commits',
  path: '/commits',
  getParentRoute: () => OwnerRepoNumberRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/$owner/$repo/$number': typeof OwnerRepoNumberRouteWithChildren
  '/$owner/$repo/$number/commits': typeof OwnerRepoNumberCommitsRoute
  '/$owner/$repo/$number/files': typeof OwnerRepoNumberFilesRoute
  '/$owner/$repo/$number/': typeof OwnerRepoNumberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/$owner/$repo/$number/commits': typeof OwnerRepoNumberCommitsRoute
  '/$owner/$repo/$number/files': typeof OwnerRepoNumberFilesRoute
  '/$owner/$repo/$number': typeof OwnerRepoNumberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/$owner/$repo/$number': typeof OwnerRepoNumberRouteWithChildren
  '/$owner/$repo/$number/commits': typeof OwnerRepoNumberCommitsRoute
  '/$owner/$repo/$number/files': typeof OwnerRepoNumberFilesRoute
  '/$owner/$repo/$number/': typeof OwnerRepoNumberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/$owner/$repo/$number'
    | '/$owner/$repo/$number/commits'
    | '/$owner/$repo/$number/files'
    | '/$owner/$repo/$number/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/$owner/$repo/$number/commits'
    | '/$owner/$repo/$number/files'
    | '/$owner/$repo/$number'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/$owner/$repo/$number'
    | '/$owner/$repo/$number/commits'
    | '/$owner/$repo/$number/files'
    | '/$owner/$repo/$number/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  OwnerRepoNumberRoute: typeof OwnerRepoNumberRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/$number': {
      id: '/$owner/$repo/$number'
      path: '/$owner/$repo/$number'
      fullPath: '/$owner/$repo/$number'
      preLoaderRoute: typeof OwnerRepoNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/$number/': {
      id: '/$owner/$repo/$number/'
      path: '/'
      fullPath: '/$owner/$repo/$number/'
      preLoaderRoute: typeof OwnerRepoNumberIndexRouteImport
      parentRoute: typeof OwnerRepoNumberRoute
    }
    '/$owner/$repo/$number/files': {
      id: '/$owner/$repo/$number/files'
      path: '/files'
      fullPath: '/$owner/$repo/$number/files'
      preLoaderRoute: typeof OwnerRepoNumberFilesRouteImport
      parentRoute: typeof OwnerRepoNumberRoute
    }
    '/$owner/$repo/$number/commits': {
      id: '/$owner/$repo/$number/commits'
      path: '/commits'
      fullPath: '/$owner/$repo/$number/commits'
      preLoaderRoute: typeof OwnerRepoNumberCommitsRouteImport
      parentRoute: typeof OwnerRepoNumberRoute
    }
  }
}

interface OwnerRepoNumberRouteChildren {
  OwnerRepoNumberCommitsRoute: typeof OwnerRepoNumberCommitsRoute
  OwnerRepoNumberFilesRoute: typeof OwnerRepoNumberFilesRoute
  OwnerRepoNumberIndexRoute: typeof OwnerRepoNumberIndexRoute
}

const OwnerRepoNumberRouteChildren: OwnerRepoNumberRouteChildren = {
  OwnerRepoNumberCommitsRoute: OwnerRepoNumberCommitsRoute,
  OwnerRepoNumberFilesRoute: OwnerRepoNumberFilesRoute,
  OwnerRepoNumberIndexRoute: OwnerRepoNumberIndexRoute,
}

const OwnerRepoNumberRouteWithChildren = OwnerRepoNumberRoute._addFileChildren(
  OwnerRepoNumberRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  OwnerRepoNumberRoute: OwnerRepoNumberRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
