/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerRepoRouteImport } from './routes/$owner.$repo'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner.$repo.index'
import { Route as OwnerRepoPullsRouteImport } from './routes/$owner.$repo.pulls'
import { Route as OwnerRepoIssuesRouteImport } from './routes/$owner.$repo.issues'
import { Route as OwnerRepoPrNumberRouteImport } from './routes/$owner.$repo.pr.$number'
import { Route as OwnerRepoPrNumberIndexRouteImport } from './routes/$owner.$repo.pr.$number.index'
import { Route as OwnerRepoPrNumberFilesRouteImport } from './routes/$owner.$repo.pr.$number.files'
import { Route as OwnerRepoPrNumberCommitsRouteImport } from './routes/$owner.$repo.pr.$number.commits'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoRoute = OwnerRepoRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoPullsRoute = OwnerRepoPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoIssuesRoute = OwnerRepoIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoPrNumberRoute = OwnerRepoPrNumberRouteImport.update({
  id: '/pr/$number',
  path: '/pr/$number',
  getParentRoute: () => OwnerRepoRoute,
} as any)
const OwnerRepoPrNumberIndexRoute = OwnerRepoPrNumberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRepoPrNumberRoute,
} as any)
const OwnerRepoPrNumberFilesRoute = OwnerRepoPrNumberFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => OwnerRepoPrNumberRoute,
} as any)
const OwnerRepoPrNumberCommitsRoute =
  OwnerRepoPrNumberCommitsRouteImport.update({
    id: '/commits',
    path: '/commits',
    getParentRoute: () => OwnerRepoPrNumberRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/pr/$number': typeof OwnerRepoPrNumberRouteWithChildren
  '/$owner/$repo/pr/$number/commits': typeof OwnerRepoPrNumberCommitsRoute
  '/$owner/$repo/pr/$number/files': typeof OwnerRepoPrNumberFilesRoute
  '/$owner/$repo/pr/$number/': typeof OwnerRepoPrNumberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/pr/$number/commits': typeof OwnerRepoPrNumberCommitsRoute
  '/$owner/$repo/pr/$number/files': typeof OwnerRepoPrNumberFilesRoute
  '/$owner/$repo/pr/$number': typeof OwnerRepoPrNumberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/$owner/$repo': typeof OwnerRepoRouteWithChildren
  '/$owner/$repo/issues': typeof OwnerRepoIssuesRoute
  '/$owner/$repo/pulls': typeof OwnerRepoPullsRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/pr/$number': typeof OwnerRepoPrNumberRouteWithChildren
  '/$owner/$repo/pr/$number/commits': typeof OwnerRepoPrNumberCommitsRoute
  '/$owner/$repo/pr/$number/files': typeof OwnerRepoPrNumberFilesRoute
  '/$owner/$repo/pr/$number/': typeof OwnerRepoPrNumberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/$owner/$repo'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/'
    | '/$owner/$repo/pr/$number'
    | '/$owner/$repo/pr/$number/commits'
    | '/$owner/$repo/pr/$number/files'
    | '/$owner/$repo/pr/$number/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo'
    | '/$owner/$repo/pr/$number/commits'
    | '/$owner/$repo/pr/$number/files'
    | '/$owner/$repo/pr/$number'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/$owner/$repo'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/pulls'
    | '/$owner/$repo/'
    | '/$owner/$repo/pr/$number'
    | '/$owner/$repo/pr/$number/commits'
    | '/$owner/$repo/pr/$number/files'
    | '/$owner/$repo/pr/$number/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  OwnerRepoRoute: typeof OwnerRepoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo': {
      id: '/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo'
      preLoaderRoute: typeof OwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/pulls': {
      id: '/$owner/$repo/pulls'
      path: '/pulls'
      fullPath: '/$owner/$repo/pulls'
      preLoaderRoute: typeof OwnerRepoPullsRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/issues': {
      id: '/$owner/$repo/issues'
      path: '/issues'
      fullPath: '/$owner/$repo/issues'
      preLoaderRoute: typeof OwnerRepoIssuesRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/pr/$number': {
      id: '/$owner/$repo/pr/$number'
      path: '/pr/$number'
      fullPath: '/$owner/$repo/pr/$number'
      preLoaderRoute: typeof OwnerRepoPrNumberRouteImport
      parentRoute: typeof OwnerRepoRoute
    }
    '/$owner/$repo/pr/$number/': {
      id: '/$owner/$repo/pr/$number/'
      path: '/'
      fullPath: '/$owner/$repo/pr/$number/'
      preLoaderRoute: typeof OwnerRepoPrNumberIndexRouteImport
      parentRoute: typeof OwnerRepoPrNumberRoute
    }
    '/$owner/$repo/pr/$number/files': {
      id: '/$owner/$repo/pr/$number/files'
      path: '/files'
      fullPath: '/$owner/$repo/pr/$number/files'
      preLoaderRoute: typeof OwnerRepoPrNumberFilesRouteImport
      parentRoute: typeof OwnerRepoPrNumberRoute
    }
    '/$owner/$repo/pr/$number/commits': {
      id: '/$owner/$repo/pr/$number/commits'
      path: '/commits'
      fullPath: '/$owner/$repo/pr/$number/commits'
      preLoaderRoute: typeof OwnerRepoPrNumberCommitsRouteImport
      parentRoute: typeof OwnerRepoPrNumberRoute
    }
  }
}

interface OwnerRepoPrNumberRouteChildren {
  OwnerRepoPrNumberCommitsRoute: typeof OwnerRepoPrNumberCommitsRoute
  OwnerRepoPrNumberFilesRoute: typeof OwnerRepoPrNumberFilesRoute
  OwnerRepoPrNumberIndexRoute: typeof OwnerRepoPrNumberIndexRoute
}

const OwnerRepoPrNumberRouteChildren: OwnerRepoPrNumberRouteChildren = {
  OwnerRepoPrNumberCommitsRoute: OwnerRepoPrNumberCommitsRoute,
  OwnerRepoPrNumberFilesRoute: OwnerRepoPrNumberFilesRoute,
  OwnerRepoPrNumberIndexRoute: OwnerRepoPrNumberIndexRoute,
}

const OwnerRepoPrNumberRouteWithChildren =
  OwnerRepoPrNumberRoute._addFileChildren(OwnerRepoPrNumberRouteChildren)

interface OwnerRepoRouteChildren {
  OwnerRepoIssuesRoute: typeof OwnerRepoIssuesRoute
  OwnerRepoPullsRoute: typeof OwnerRepoPullsRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
  OwnerRepoPrNumberRoute: typeof OwnerRepoPrNumberRouteWithChildren
}

const OwnerRepoRouteChildren: OwnerRepoRouteChildren = {
  OwnerRepoIssuesRoute: OwnerRepoIssuesRoute,
  OwnerRepoPullsRoute: OwnerRepoPullsRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
  OwnerRepoPrNumberRoute: OwnerRepoPrNumberRouteWithChildren,
}

const OwnerRepoRouteWithChildren = OwnerRepoRoute._addFileChildren(
  OwnerRepoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  OwnerRepoRoute: OwnerRepoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
